<?php
// auto-generated by sfSecurityConfigHandler
// date: 2012/04/18 13:33:56
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'superadmin',
      ),
    ),
  ),
);
