<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/11/18 11:33:42
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'calendario_admin',
        1 => 'admin',
      ),
    ),
  ),
);
