<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/11/18 11:33:42
sfConfig::add(array(
  'mod_calendario_admin_enabled' => true,
  'mod_calendario_admin_view_class' => 'sfPHP',
));
