<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/11/17 22:10:14
sfConfig::add(array(
  'mod_aslideshowslot_enabled' => true,
  'mod_aslideshowslot_view_class' => 'sfPHP',
));
