
# A homepage rule is expected by a and various other plugins,
# so be sure to have one

homepage:
  url:  /
  param: { module: a, action: show, slug: / }


calendar_events:
  url:  /calendar_events
  param: { module: aBlogSlot, action: calendarEvents }


contacto_index:
  url:  /
  param: { module: contacto, action: index }
  class: aRoute
contacto_sent:
  url:  /sent
  param: { module: contacto, action: sent }
  class: aRoute
contacto_action:
  url: /:action
  param: { module: contacto }
  class: aRoute

calendario_index:
  url:  /
  param: { module: calendario, action: index }
  class: aRoute

calendario_action:
  url: /:action
  param: { module: calendario }
  class: aRoute


calendario_admin_index:
  url:   /admin/calendario
  param: { module: calendario_admin, action: index }

calendario_admin_edit:
  url:   /admin/calendario/:fecha
  param: { module: calendario_admin, action: edit }
  requirements:
    fecha: \d+


reserva_index:
  url:  /
  param: { module: reserva, action: index }
  class: aRoute

reserva_sent:
  url:  /sent
  param: { module: reserva, action: sent }
  class: aRoute

reserva_action:
  url: /:action
  param: { module: reserva }
  class: aRoute

login:
  url: /login
  param: { module: sfGuardAuth, action: signin }


# A default rule that gets us to actions outside of the CMS.
# Note that you can't have pages with a slug beginning with /admin
# on a site that uses this particular rule. You could use a 
# different prefix. Or you could provide rules for every
# module, or even for every action. This is just the simplest way.

default:
  url:   /admin/:module/:action/*

  
# Put any routing rules for other modules and actions HERE,
# before the catch-all rule that routes URLs to the
# CMS by default.

# Must be the last rule
a_page:
  url:   /:slug
  param: { module: a, action: show }
  requirements: { slug: .* }


