<?php

/**
 * aMediaItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    asandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
class aMediaItem extends PluginaMediaItem
{

  public function getEmbedCode($width, $height, $resizeType, $format = 'jpg', $absolute = false, $wmode = 'opaque', $autoplay = false, $options = array())
  {
   $resizeType = 'c';
    if (($this->getType() == 'image') && $this->service_url){
      $this->service_url = null;
    }
    return parent::getEmbedCode($width, $height, $resizeType, $format, $absolute, $wmode, $autoplay, $options);
  }


}
